spring.datasource.url=jdbc:postgresql://dpg-d4re1ov5r7bs73f73th0-a.singapore-postgres.render.com:5432/todo_db_vyr1
spring.datasource.username=root
spring.datasource.password=nUCwQb9a7h5CVCyzRx0p5ZJIGbzpjbL1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
